### ISSUE TITLE
Generating single value primary keys for dimensions

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#109]
Dimensions can be made of multiple attributes.  Linking from the [fact table](https://en.wikipedia.org/wiki/Fact_table), a [dimension table](https://en.wikipedia.org/wiki/Dimension_table) can have a primary key that points to some set of these attributes (a composite key).  Currently, the `primaryKey` for a [dimension](http://fiscal.dataprotocols.org/spec/#dimensions) is defined as either a string referencing the name of a single attribute in a dimension **or** an array of such strings.  However, there is concern that expressing a composite key through an array is not ideal or explicit for implementers (https://github.com/openspending/babbage/issues/6, https://github.com/openspending/fiscal-data-package/issues/93#issue-120033382), and that we should instead restrict `primaryKey` to a single value and provide guidance on how such a key could be generated.  Some background: https://github.com/openspending/fiscal-data-package/issues/96

Below are a few of the options for achieving this:

### Option 1 ("autoincrement") https://github.com/openspending/fiscal-data-package/issues/96#issuecomment-162576573
Cons:
* opaque
* changes each time we generate the dimension table
* not usable for URLs

edit: how an generated key could be generated in the mapping
```
constant: “autoincrement”
```

### Option 2 (“composite string”) https://github.com/openspending/fiscal-data-package/issues/96#issuecomment-162598473
*i.e. generate a composite like level1::level2 or A::01::2003 (need URL-safe separator)*

Cons:
* Not clear what happens if classification values change (e.g. A.01 morphs to become B.02) 

edit: how an generated key could be generated in the mapping
```
constant: “%(level1_name):::%(level2_name)”
```

**Comment by pwalsh** [comment]
Hey @danfowler great, this is a very important thing to solve. 

As Option 2 above is based on my post in https://github.com/openspending/fiscal-data-package/issues/96#issuecomment-162598473 I want to be a bit more explicit about that on a few points, both pros and cons:

**Pros**

* Any data storage can potentially (re)create the same primary key. This is so, so important for a distributed system like OpenSpending Next, and opens up the possibility that `rgrp/cra/{primary_key}` can mean the same thing in various databases.

**Cons**

* You probably can't just concat (or hash) the values. We probably need keys so that order is not a factor. So, we might expect implementors to create a pk which is actually a JSON string with sorted key order or something if we need to guarantee some type of consistency of representation using the data itself as the seed. As we can see, this gets complicated fast, and is probably beyond the scope of a data standard/spec.


About your con: 

    Not clear what happens if classification values change (e.g. A.01 morphs to become B.02)

I'm not sure that is an issue at all: such a change is significant - it is a new object for all intents and purposes and therefore I don't see the scenario where the fact that the pk would change would be an issue.

### Other thoughts

1. As most commenters over the various issues do seem to agree that we can't possibly expect the pk of any dimension to be explicit in a field of data, I'm wondering if we do in fact need to deep dive into the implementation of how pks are generated (not sure)?
2. We have to be very aware about what this means for parent / child relations. If pk is generated from data, what does the `parent` reference point to exactly?

**Comment by pwalsh** [comment]
https://github.com/openspending/fiscal-data-package/issues/110#issuecomment-167059682 may be of interest here.

**Comment by rgrp** [comment]
@danfowler could you inline into the comment the description the concrete example of how this would be done in the mapping for each of the two cases. I think this would help discussion.

**Comment by danfowler** [comment]
So, greater context.  As of [this commit](https://github.com/openspending/fiscal-data-package/commit/a4da82960a12d0246edfc428cceaa98923f3aff6), `primaryKey` in Fiscal Data Package has been defined as a list of column names in line with JSON Table Schema (here's an interesting discussion about that feature: https://github.com/dataprotocols/dataprotocols/issues/21).  The issue under discussion here is whether this is a Bad Thing.  Regarding generating a single `primaryKey`, there seems to be very little support for an "autoincrement" solution, and concatenating columns to generate a new `primaryKey` could get very complicated (and we still need to fully flesh out the value of that approach).  Arguably, whatever decision we make about the wisdom of the current `primaryKey` in FDP should trickle up to [JSON Table Schema](http://dataprotocols.org/json-table-schema/) so that they remain in alignment.

**Ways forward:** (not independent of each other, feel free to suggest others)

- Drop the issue of single `primaryKey` generation as out of the scope of the spec
- Leave `primaryKey` defined in Fiscal Data Package as it currently is
- Revisit how `primaryKey` is defined in [JTS](http://dataprotocols.org/json-table-schema/).

@pwalsh @rgrp @pudo @akariv wdyt?

---

btw @pwalsh I'm not sure I understand this: 

> We have to be very aware about what this means for parent / child relations. If pk is generated from data, what does the parent reference point to exactly?

**Comment by pwalsh** [comment]
@danfowler some points

1. This issue is still phrased in terms of primary key for *dimensions*, but as far as I see we need to solve this for each dimension, and the budget line itself.
2. `primaryKey` in an FDP model is not necessarily 1-1 with `primaryKey` in JSON Table Schema - let's not tie them explicitly unless you can make a strong case for why it is the same thing. My case for this is related to my next point.
3. In FDP `model`, `pk` is currently a top-level property of a dimension, for example. Yet, dimensions can express hierarchy, and therefore (can) unpack into an array of rows. `pk` doesn't make much sense to me in FDP, in the current spec, because of this. See [here](https://github.com/openspending/fiscal-data-package/issues/112) for a description of some of my confusion when trying to write a star schema data model around it (I'm aware that in the case of babbage, the data stays flat and maybe the issue gets "hidden" due to the way we actually break up dimensions to store then in a babbage model).

For the point on parent / child relations: I'm not sure how it is confusing, but I'll try to unpack it:

* in a single dimension, we express parent-child relations
* that essentially provides the means to turn a denormalised structure into a normalised one
  * i.e.: there can be multiple "rows" of data in a single dimension
  * e.g.: in a star schema, you'd likely push the parent-child relations into a dimension table, and the fact table would just have a foreign key to the most specific dimension object
* So, the current `pk` spec for FDP "works" to make such a foreign key, *as long as* it identifies the most specific dimension object
* And, the current `pk` spec for FDP "fails" because the `parent` pattern does not follow the `pk` pattern, and therefore may not be using an accurate identifier

**Comment by danfowler** [comment]
@pwalsh thanks, that was super helpful.  So, in the case where `parent` is used in a dimension, a hierarchy of attributes is expressed which could, as a composite, serve as the primary key for that dimension.  Enforcing an explicit `primaryKey` on that dimension is then redundant, or worse, in conflict with the `primaryKey` expressed implicitly through `parent`.  Do I have that right?

BTW, when you say "rows", you mean "columns", right?

**Comment by pwalsh** [comment]
@danfowler no, I definitely mean "rows". If it was "columns", then it would not (necessarily) mean a parent-child relationship, but rather just attributes of an object. 

To be clear, if I did mean columns, then I don't think there is an issue, and if you say I'm trying to bend the spec too much, then, maybe I am and I'm drop this line of investigation :). 

But, as we have an OLAP cube here, I'm thinking in terms of star schemas.

Simple example of using FDP to (try to) create a star schema:

```
# budget.csv
budget,admin1_code,admin1_name,admin2_code,admin2_name
10,X100,Education,X110,Primary Schools
20,X200,Aged Care,X210,Hospices

# FDP snippet

model: {
  measures: { amount: { field: 'budget'} },
  dimensions: {
        admin: {
          dimensionType: 'classification',
          classificationType: 'administrative',
          attributes: { 
            id: { field: 'admin1_code' }, 
            title: { field: 'admin1_name', label_for: 'id' },
            id2: { field: 'admin2_code', parent: 'id' }, 
            title2: { field: 'admin1_name', label_for: 'id2' }
            // in order to create a star schema, I'd follow the parent relations, ignore the `*2` attribute names, and use the attribute names of the top level of the hierarchy. No other way to do a star schema with FDP the way it works now. See how that translates into a database below.
          }
        },
  }
}

# star schema as simple javascript object, a dimension on the fact table is a foreign key to an object in the dimension table

let database = {
  facts: [
    {amount: 10, admin: 'X110'},
    {amount: 20, admin: 'X220'}
  ],
  dimensions: {
    admin: [
      {id: 'X100', title: 'Education', parent: null},
      {id: 'X110', title: 'Primary Schools', parent: 'X100'},
      {id: 'X200', title: 'Aged Care', parent: null},
      {id: 'X210', title: 'Hospices', parent: 'X200'}
    ]
  }
}
```

**Comment by akariv** [comment]
They way I see it, it's quite alright to have a primary key to span over a few columns in the data.

In such cases, I'd say that the order of the columns in the `primaryKey` attribute implicitly dictates some sort of hierarchy (which means that the `parent` might be redundant here). However, it's not always correct to assume that the lowest level in the hierarchy (i.e. the leaves) have unique values which identify the entire path above them.
For example, you could have:
 - 01.Education > 01.Primary Schools > 01.Administration
 - 02.Aged Care > 01.Hospices > 01.Administration

You need the entire path ('01.01.01' vs. '02.01.01') to understand the exact hierarchy.

Same goes for dates (if you consider 'year', 'month' and 'day' to be parts of a hierarachy as well)

Therefore, I would implement the star schema a little bit differently:
```
let database = {
  facts: [
    {amount: 10, admin: ['X100','X110']},
    {amount: 20, admin: ['X200','X220']}
  ],
  dimensions: {
    admin: [
      {id: 'X100', title: 'Education', parent: null},
      {id: 'X110', title: 'Primary Schools', parent: 'X100'},
      {id: 'X200', title: 'Aged Care', parent: null},
      {id: 'X210', title: 'Hospices', parent: 'X200'}
    ]
  }
}
```

**Comment by pwalsh** [comment]
@akariv yes, agreed that is also a possibility. In previous implementation of the same sort of thing in Israel we build paths, similar to what you are doing with the array.

**Comment by danfowler** [comment]
So when the dimension is comprised of attributes that exist in a hierarchy, then only `parent` can be relied on to generate a `primaryKey` in a star schema.  

We must use the full path to the budget item (i.e. a composite key) as a key because the most specific level of a categorization is not guaranteed to be unique.

However, not all attributes within a dimension will exist within a hierarchy, so `parent` can't necessarily be relied on to generate the `primaryKey`. In that case, we can just use all attributes of a dimension as the key.

So perhaps `primaryKey` should go away.  Thoughts @rgrp?

**Comment by akariv** [comment]
This is mostly an implementation issue (as stated in the issue's description).
Until an implementor comes with a concrete modification suggestion, I move to close this on 'theoretical discussion' grounds. 
Any objections?

**Comment by rgrp** [comment]
INVALID / WONTFIX / FIXED. This was more of a discussion than any request for a change in the spec. It is also as @akariv says an implementation detail and we can leave to implementors.
