### ISSUE TITLE
rename "source" to "field" in measures and dimensions

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package#114]
* https://github.com/openspending/fiscal-data-package/issues/93
* https://github.com/openspending/fiscal-data-package/issues/93#issuecomment-168145432

Now that:

1. We changed `fields`-> `attributes` inside `mapping` to have clear conceptual distinction between physical and logical models
2. We added the ability to map logical `attributes` to a `constant`

I think we can tighten up our terminology by renaming `source` to `field`: Attributes always map to a field or a constant.

**Comment by rgrp** [comment]
@pwalsh what is exact benefit here? My sense is that `source` is more meaningful than `field` - indicating that data here comes from `source` elsewhere. I guess `sourceField` would be most meaningful but perhaps a bit ugly.

I'm just asking because this is a major breaking change for what seems like fairly minor reasons and which does not necessarily improve understanding or consistency. If you could take a couple of minutes to spell out the benefits a bit more than would be great :-)

**Comment by pwalsh** [comment]
@rgrp so, for me the benefits are:

1. `source` and `field` currently mean the same thing - the name is just different based on whether it is in the `mapping` or a JTS `schema` on a resource
2. Seeing as we accepted `constant`, it seems to me semantically accurate to be able to say "the *source* of an attribute can be a `field` or a `constant`"

I won't loose sleep over this one if we reject, but I do think it brings a little more clarity.

**Comment by danfowler** [comment]
> I'm just asking because this is a major breaking change for what seems like fairly minor reasons and which does not necessarily improve understanding or consistency.

@rgrp I think it could improve both understanding and consistency if we are able to write the spec such that `field` unambiguously refers to a column on the source CSV throughout, whether in the `schema` or `mapping`.

**Comment by rgrp** [comment]
WONTFIX. At the moment my inclination is that `source` is actually better - `sourceField` might be best but not worth the change. Not totally certain here but this seems minor and so inclined to go with status quo.
