### ISSUE TITLE
Geocode field needs a better explanation

### ISSUE THREAD

**Issue by trickvi** [openspending/fiscal-data-package#12]
Currently the geocode field is just a string with "name" of area. That needs better explanation because this just invites too many interpretations.

**Comment by danfowler** [comment]
INVALID. with the refactor in #34 and associated work in v0.3 this is no longer valid.

See: http://fiscal.dataprotocols.org/spec/#location

**Comment by joshuacpowell** [comment]
This is great - but no field for latitude/longitude or other geometry? Using only codes without geometry presents additional steps to potential users of the data to create maps/visualizations.

**Comment by danfowler** [comment]
@joshuacpowell thanks!  Part of the reason I closed the issue is that there is no longer an explicit `geocode` field and the initial problem has been resolved.

But I think you make a good point for adding recommendations for latitude/longitude fields in a location dimension.  Can you open up a new issue with your above comment?

**Comment by joshuacpowell** [comment]
Done: https://github.com/openspending/fiscal-data-package/issues/79
