### ISSUE TITLE
suggestion to change country code from recommend to required

### ISSUE THREAD

**Issue by hoonch3** [openspending/fiscal-data-package#127]
Unlike other interntional open data, I think politics or fiscal data should contain 'country code' for user to understand where this data is from. 

people might be confused where it comes from among countries using English, 
people might be confused among countries using different languages when they try to translate the data into a differen laguage.

**Comment by danfowler** [comment]
Thanks @hoony for the suggestion! We try to carefully limit the number of `required` elements to only those that are **absolutely** necessary to model fiscal data.  In this case, we can generate a model and visualize the data without necessarily knowing which country it is from.  Knowing the country for given dataset is certainly helpful and would reduce confusion, which is why I'm in favor of keeping it as a `recommended` element.

**Comment by hoony** [comment]
I got it, I didn't consider the limit the number of `required` elements.

It would be good to show the criteria among `required`, `recommended`, and `option` for people who wannt use fiscal-data-package.

Thanks!

**Comment by danfowler** [comment]
@hoony that's a great suggestion :+1:

**Comment by danfowler** [comment]
Hi, @hoony, I am moving to close this. We'll can probably introduce this information in a later version of the spec.

**Comment by akariv** [comment]
@danfowler can we close this? Is there an issue for @hoony's suggestion?

**Comment by rgrp** [comment]
FIXED / WONTFIX. Not sure anything remaining to fix here. We do need a tutorial where we can walk through what is required etc but that is another issue.
