### ISSUE TITLE
Declaring type and status on each resource: why?

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package#32]
The spec requires a type for each resource, where type is one of "expenditure" or "revenue".

The spec requires a status for each resource, where status is one of "proposed", "approved", "adjusted" or "executed".

This pattern can lead to large amounts of repeated data.

Example:

I have a large dataset of local budgets in a country. For each "item" in a budget, my structure is like:

* code: the unique identifier of the item
* name: the name of the item
* description: a text description of the item
* type: "revenue" or "expenditure"
* budget_amount: "approved" (the approved proposed budget)
* actual_amount: "executed" (what was actually spent)

Note that, with Budget Data Package, I'd be required to:

* have four distinct CSV files (and/or data packages) instead of one
* repeat code, name, and description in 4 different places (more room for error, etc.)

I'm wondering:

1. Is there a use case that the spec aims to support that I don't grok?
2. If not, how could the spec be adjusted to deal with my use case (which I do not believe is unique)

**Comment by pwalsh** [comment]
cc @tryggvib @rgrp

**Comment by tryggvib** [comment]
The reasons for taking this approach have mainly to do with publication process (and also partly users). Your use case is based on wrangling the data after the fact (the execution) while budget data packages were designed to make the publication as easy as possible (but you're correct in that it's more error prone).

Budget data packages can be published at any stage in the process and may change between publications. So there might be 5 proposed budgets, then one approved. Then there might be 3 adjusted budgets and then we have one executed budget. This could be mapped to 10 resources in a single package, but mapping it into a csv file via headers will soon become painful and you'd probably have to start versioning a resource which is harder for publishers to do and maintain (they don't use version control or something like that) and it'll become harder to follow the budget process from start to finish.

That was the main reason (about difference in revenue and expenditure, that was only because there's a different set of data collected for each one).

This might not be the best decision (after all it's just a draft) so let's open a discussion about this.

**Comment by pwalsh** [comment]
Ok, that makes things clearer for `status`. An issue I was pondering was state transition (e.g.: proposed > accepted > adjusted > accepted > executed), and how you have explained it makes a lot of sense (although, consumers would have to rely on, say, `fiscalYear` and `datePublished` in order to build a sequence, right?).

About `type` I'm less sure: at least in the data I have (government budget data for Australia and Israel), revenue and expenditure are part of the same publication. I'd be interested to know if this is not common across the board, for `aggregate` spend data at least.

**Comment by pwalsh** [comment]
And, I guess if repetition is an issue, (technical) users could use foreignKey support in JSON Table Schema to get around that...

**Comment by tryggvib** [comment]
Yes they'd have to rely on fiscalYear and datePublished in order to build the sequence.

About type, it becomes difficult in a few cases, e.g. classification. Cofog works well for where money is spent (this money is being spent on hospitals) but not for where money comes from (VAT revenue doesn't fit into Cofog). This is why the classification for revenue is only economical ``gfsmExpense``. Besides that, then from the ``aggregate`` point of view it's very much the same.

From the ``transactional`` end it's also almost the same (except classification) and the required "supplier" field.

**Comment by pwalsh** [comment]
@rgrp @trickvi I'm interested in the original issue I raised again, in light of v0.3. `type` is now `direction`, but the general gist of my issue is the same (and let's just focus on the issue of `direction` for now, for clarity).

How can we support a case where a single file has budget lines with both directions?

Or, from another angle, do we want to support `direction` in any/all of the following places?

1. On the top-level descriptor, as it currently is, whereby all resources comply
2. On each resource, where every line in the resource complies
3. Inside the data (CSV) where a column indicates direction on a per-line basis
4. All of the above, resolving from most specific to least specific?

**Comment by rgrp** [comment]
INVALID. No longer valid with refactor in v0.3.
