### ISSUE TITLE
On "direction"

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package#37]
`direction` is currently declared at the package level, indicating one of revenue or expenditure.

* Should we consider it as a property of resources?
  * Should we allow both, where a declaration on a resource overrides that of the package?
* If there is no default, how should the data be understood in the absence of the `direction` property?

**Comment by stevage** [comment]
Thanks for bringing this up. I've just run into this as I attempt to make a datapackage for data that includes assets, liabilities, revenue and expenses in one. There are three choices of level:

- at the data package level. This is very limiting for my purposes, and means that I would need one package for expenses, and a whole separate one for revenue, another one for assets, etc.
- at the resource level. This is better, but it still means you can't handle a single CSV file which contains both revenues and expenses, for instance. That doesn't sound contrived to me, if the data is already aggregated.
- at the dimension level. For instance:

```
    "description": "",
    "mapping": {
        "measures": {
            "expenditure": {
                "source": "Expenses",
                "currency": "USD",
                "direction": "expenditure"
            },
            "revenue": {
                "source": "Revenue",
                "currency": "USD",
                "direction": "revenue"
            },
...
```

IMHO, "direction" is a semantic property, and hence belongs to the measure, not to the resource. For instance, you can imagine a CSV file that contains transactions between two organisations. There is no single absolute "direction", but from each of their perspectives there is.

> Should we consider it as a property of resources?

IMHO, no, because it's not a property of the "physical" structure.

> Should we allow both, where a declaration on a resource overrides that of the package?

Should we allow declarations on both a dimension, and on the package? Useful, but it adds complexity. OTOH, if we don't, it will be annoying for vast majority of packages in which all fields do "point" the same way.

>If there is no default, how should the data be understood in the absence of the direction property?

Well, it is called "open **spending**".

Perhaps we should consider it sort of like `factor` - it defaults to 1 (expenditure), but you can override it to `-1` (income)...

**Comment by rgrp** [comment]
@stevage i think you are spot on here in the analysis - this is almost certainly a property of the measure.

One  thought though, like, fiscalPeriod I wonder if we want a top level summary metadata item which is an array which lists the various options that apply - this is more for easy access. That said I always dislike duplication since stuff gets out of sync.

So my instinct, right now is to move this to the measure.

@pwalsh @danfowler @stevage any thoughts before i proceed?

**Comment by pwalsh** [comment]
I agree that it is a property of a given measure.

I don't like the duplication at top-level of data package. This mirrors my comments on `fiscalPeriod` [here](https://github.com/openspending/fiscal-data-package/issues/59#issuecomment-147101990). 

I find it confusing that some things will be declared in a measure or a dimension, and *also* maybe declared at the top level of the data package. In thinking about how people will use the spec, and how I will write code that uses it, I'm really looking for a single point of truth on any one property.

**Comment by danfowler** [comment]
I will also add that `status` (`budgetPhase`) https://github.com/openspending/fiscal-data-package/issues/38, in addition to `fiscalPeriod` and `direction`, seems to apply naturally at the level of a given measure.  I understand that it would be nice to have some of this metadata at the top-level for easy access, but I generally agree with @pwalsh that to the extent possible, this information should reside in the one place where it is most directly relevant (e.g. measure).

**Comment by rgrp** [comment]
Resolved that this will move to measure.
