### ISSUE TITLE
Nesting dimensions under mapping

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-package#43]
https://github.com/openspending/fiscal-data-package/blob/master/spec/index.md#details

We nest measures `mapping.measures`. I think we should do the same for dimensions: `mapping.dimensions`. 

It is more consistent in terms of the spec, and means that code that works with the spec does not need to  special case "measures" in order to work out what under `mapping` is a dimension.

cc @trickvi

**Comment by trickvi** [comment]
First of all, I don't think introducing OLAP concepts in the data package is beneficial. It makes too big of an assumption about how everything will be processed.

Second, and more specific to this topic, this is largely caused by the fact that the property names for dimensions (and also measures) are unknown meaning you have to process the dimensions and measures differently than almost everything else, you don't get the measure and dimension name from a value, they are the key (which is for instance really bad for the schema).

For dimensions you have to pick them out as any key which is not "measures". A minor problem you'd run into is if you have a dimension called "measures" (for some reason). That would be impossible to do.

**Comment by pwalsh** [comment]
OLAP aside, the whole point of the issue is to deal with the `measures` special casing that would currently be required.

The OLAP issue does not go away though, from all directions. Are you saying that just because I use the word "dimensions" it suggested we are tied to OLAP (but measures is ok)?

**Comment by pudo** [comment]
Making "may not look anything like OLAP or use any of it's vocabulary, because we think that's heavy-weight" is a particularly creative method of actively shooting yourself in the foot.

**Comment by pwalsh** [comment]
@pudo you lost me (or do you mean in response to @trickvi's comment that we shouldn't use OLAP concepts?).

**Comment by pudo** [comment]
Sorry, yes it was in response to @trickvi's comment.

**Comment by trickvi** [comment]
I don't understand what you mean @pudo

What I mean is I don't want to know from the spec how to compile source fields into a bigger entity (dimension). I want to know where I can get the information I need from, e.g. the payee identifier. Sure the dimensions do have a primaryKey which should indicate what field to go by, but that's an especially convoluted way of getting the identifier.

**Comment by pudo** [comment]
Yeah, we're not talking about the same thing I guess. I do want to get "bigger entities", with PKs. I have no idea what a payee identifier is. So I'll leave you to it. In any case, does OKFN plan any sort of public consultation on this standard?
