### ISSUE TITLE
What is the contribution model for this standard?

### ISSUE THREAD

**Issue by pudo** [openspending/fiscal-data-package#45]
I've been trying to engage in the design of this standard over the last year or so, but it's entirely unclear to me how contributions actually make it into the spec. Tickets from non-OKFN contributors are closed randomly, and I can't tell if much (if any) external feedback is ever incorporated.

Right now, I can see two scenarios: 

a) This standard is not intended for public consultation. It is built for it's customers (the World Bank, IMF) and the implementing organisation (OKFN) as an internal measure. 

or:

b) If this is to be an open standard, a clear channel for contributions, which is fully valid for all members of the project and defines how changes are incorporated into the standard, is required. This can be restrictive (i.e. contributions are accepted only from accredited contributors), but it would need to be spelled out.

Right now, I see a real risk that this standard will in effect be made through method (a) but then advertised as if it were the outcome of an open process (b). This would undermine the notion of "open standards" and discredit OKFN as a participant in standards processes.

cc @rgrp @pwalsh @jpmckinney

**Comment by jpmckinney** [comment]
The process should also set reasonable deadlines for providing a response to feedback, e.g. I have 6 issues opened a year ago, without any comments by editors: https://github.com/openspending/fiscal-data-package/issues/created_by/jpmckinney

**Comment by rgrp** [comment]
@pudo first, as it seems a concern, what issues are "closed" randomly? Also I don't think there is any "bias" one way or the other to specific contributors - if issues are closed randomly i think it is without any specific selection ;-)

Strictly, I don't know what an "open" process would exactly mean. Right now, *anyone* may have input or comment on the standard but not everyone gets an equal say i.e. we don't vote things in by majority or even consensus. Reading your comments I get sense that more formal voting on changes would occur based on some kind of "accredited" contributor model. I'm not sure how exactly how that would work.

Personally, and this me speaking out loud, I think you need to have some kind of "benevolent" dictator model with these benevolent dictators being your editors. They take input from everyone, but ultimately make decisions about what go in and out. The process is open in that anyone may make comments, but it isn't open in that there is democracy about how changes go in (though I do think you can have voting etc - it is just that ultimately the editors make the decision informed but not based on that voting).

I think this model avoids "design by committee" and very long drawn out processes. It does place significant responsibility on the editor(s) to do a good job of incorporating different concerns. And ultimately it is the editors job to find good solutions and good compromises. (You also avoid the risk of "democracy" model that those who turn up to have input do *not*, in fact, represent end users at all - editors can be clear they have a wider responsibility).

Obviously, one can add to this model, e.g. by appointing an Advisory Board and this is something that should happen soon.

Obviously many other models are possible - plus tweaks to the "editor" model. Let me know what you think would best lead to producing a great spec here :-)

## Background

Regarding overall process here it may be worth sharing some info:

- We produced a v0.1 a year ago based on consultation with various stakeholders. Activity then went into hibernation, in part because external stakeholders were evolving (e.g. GIFT being setup) and partly because specific resource support for OK to coordinate work on this stopped. Thus many comments made on v0.1 were not resolved.
- As of May this year, GIFT were fully operational, and there was some support again to work actively on this. Hence since May we've been able to restart here. One thing that we concluded based on initial feedback was that the model of requiring a strict data structure was probably not right vs a mapping model. Thus, focus of work for v0.3 alpha was a significant rework.
- That has now happened and we are now in a position to really start working through the outstanding issues.

@jpmckinney this explains why a bunch of comments from last Autumn have not been resolved until now: a combination of hiatus whilst we got feedback and had a backing group in place plus the fact that we did a substantial rework.

PS: @pudo as you know we don't use the OKFN acronym anymore ;-)

**Comment by pudo** [comment]
Thanks @rgrp for this response.

To be clear about my primary ask: that the process for contributing to FDP (whatever it may be) be spelled out and adhered to, so that potential contributors can make an informed decision on whether to engage or abstain.

Any process should consider the following aspects:

* There is diversity in the purposes for which users want to work with fiscal data. Any standard will need to balance these interests.

* The standard must account for diversity in the processes and institutions which produce and release fiscal information.

* In the interest of sustainability and innovation, the process should avoid a "single implementor enforced by government" outcome. This is part of why "open government" exists.

* The [home page](http://fiscal.dataprotocols.org/) claims that this standard is made for "researchers and journalists", so a mechanism should exist for incorporating their concerns.

* It is much harder to involve contributors to fix an existing specification after it's release than it is to be inclusive from the start.

The model which you propose (i.e. BDFL) is appropriate for some free software projects. It does not seem to me to be suited for a complex, political task like fiscal data standardisation.

In short, I think more "design by committee" is exactly what you need. If that ends up being a drawn out process, then maybe it's because you're trying to stuff data produced by thousands of government entities into a spreadsheet which is then used for goals as different as data visualisation, econometric analysis or heuristics-based corruption flagging.

It is worth noting that while major internet standards bodies have "chairs" or "editors", they follow a far more sophisticated contribution model which includes checks and balances. And yes, these do include accredited contributors, deadlines, voting and consensus. See: [W3C Process Document](http://www.w3.org/2003/06/Process-20030618/groups.html), [IETF Internet Standards Process](https://tools.ietf.org/html/rfc2026).

These are concrete governance mechanisms at your disposal, which have a well-defined effect and role. An Advisory Group would most likely not have such direct influence, thus I would describe it as a fig leaf.

To be honest with you, I must say that I feel the current document is a testament to the fact that a smaller circle of contributors will not always lead to the best technical solution. There is a lack of goal-orientation, specificity and expressiveness, all of which could be addressed by making more voices heard.

Finally, I feel that the appeal of OK is it's ability to convene, rather than to dictate. It's strength is letting people from many backgrounds explore ideas together, not to push technology onto them through the mandate of Washington organisations. Play to your strengths.

**Comment by rgrp** [comment]
@pudo thanks for the useful comments.

For my part, I'd imagine the efforts here to a relatively informal "rough consensus and running code" which would iterate fast based on trial and error and user engagement and, then, possibly feed into a more formal standardization process - perhaps elsewhere. As such, this has intentionally been quite rough, informal and lightweight - a more heavyweight process could then boot out of it. That's just been my impression so far and it could be that the heavyweight process starts operating "here" rather than in a different forum.

Asides:

* Can you suggest specific people or organizations that you think could / should be engaged right now.
* Are there quick wins on process e.g. a regular release schedule. Obviously, just now we've just done an alpha or major new version that switches to the mapping model. So we could have a target for a fully "stable" v0.3

These are some quick thoughts and I want to think more - I note I'm away for several days so don't be surprised if I'm silent for next week or so.

**Comment by pudo** [comment]
I guess it's worth putting that quote [into context](https://en.wikiquote.org/wiki/David_D._Clark): "We reject: kings, presidents and voting. We believe in: rough consensus and running code." So, it's really not consensus if there's a dictator involved ;)

What you are proposing is similar to [Office Open XML](https://en.wikipedia.org/wiki/Office_Open_XML), i.e. Microsoft Office's  document format which was submitted to ECMA after the fact. The problem with this is that when you do not hold a massive market share, there's very little incentive for third parties to engage with your standard. All major design decisions will have been made, and any fundamental changes needed to accomodate different use cases can be dismissed in order to retain backward-compatibility.

You also asked for specific people or organisations that should be involved in such a process. Here's a few proposals, in no particular order:

* Government, ie. national, state and local levels. I take it you've been working with Mexico, so a low-income country might be useful as well. EU BUDG, EU PO. US CBO. 
* Other system vendors, such as Socrata, OpenGov.com, SpendNetwork, OpenNorth, Hasadana, BudgIT, CIVIO, Sunlight, US Data Transparency Coalition. 
* Potential end-users, such as CBPP/IBP, Fundar, CRCB Hungary, Journalismfund.eu, CPI Bosnia, NRGI, KBZ Austria, INESC, CBPS India, Transparent Chennai, Fair-Play Alliance
* IFM(I)S vendors, such as Oracle, SAP.

I'm sure you've talked to many of these groups and organisations. But that doesn't replace involving them in a proper process which gives their interests the same weight as OK's.

Finally, there's a legitimate question as to why we need a budget data standard at all. After all, the stuff usually comes in spreadsheets and can be opened in Excel. Comparing budgets across different political systems and contexts is a risky proposition at best.

But using this process to create a common language between international groups, driven by the desire to make public finance data accessible to a broader public, would be a really useful goal. Maybe a more informed and connected civil society will even help avoid some future inter-state fiscal waterboarding. But that won't happen through a quick & dirty RFC.

**Comment by danfowler** [comment]
Proposal: at the very least, let's draft something that at least describes the current state of the world and what a potential contributor should expect when attempting to contribute to the Fiscal Data Package specification.  We can then place it on the homepage or at the top of the spec.

**Comment by danfowler** [comment]
@pudo I'm going to take a shot at defining something we can work with going forward.

**Comment by pudo** [comment]
Awesome! Have a look at this thing that Tim Davies drew up for OCDS: https://github.com/open-contracting/standard/issues/272

**Comment by danfowler** [comment]
Thanks @pudo!

**Comment by danfowler** [comment]
Hi @pudo @rgrp @jpmckinney I've added a PR for a set of hopefully lightweight contribution guidelines and expectations.  Please take a look:

https://github.com/openspending/fiscal-data-package/pull/122

**Comment by jpmckinney** [comment]
Looks fine to me. In terms of closing issues if time elapses, does `wontfix` mean "will never fix"? If so, it seems like the time bounds make it hard to agree on solutions to thorny issues.

**Comment by danfowler** [comment]
@jpmckinney good point!  I think there might be some issues where `wontfix` does mean "will never fix", but I'm realizing that a fair few will more likely be pushed to some future version.  I should clarify this.  Thanks.

**Comment by timgdavies** [comment]
Just to log, in line with @pudo's points above, that I do not feel the current contributing model at [https://github.com/openspending/fiscal-data-package/pull/122/files](#122) will be fit for purpose when you head towards a 1.0. 

That will need something which has a clear governance structure, checks and balances, and mechanisms to assess consensus. I don't feel those mechanisms are in place in the current model. 

That said, getting such a structure is very hard, and done prematurely, can create headaches: so suggest perhaps clarifying between the contribution model for developing **drafts** (for which the proposal seems solid), and the governance model for making a **release**, which should have a clear, and longer time-frame review process to include more stakeholders.

**Comment by pwalsh** [comment]
Moving to https://github.com/frictionlessdata/datapackage-fiscal/issues/5
