### ISSUE TITLE
Allowing arbitrary names of dimensions and their fields might lead to difficulties

### ISSUE THREAD

**Issue by marek-dudas** [openspending/fiscal-data-package#54]
It seems to me that the current version of Fiscal Data Package (0.3.0-alpha2) defines only the form of dimensions and measures in the mapping, but not their content or semantics: the creator of a data package can use any, arbitrary, names for dimensions and their fields. If that is so, it could be quite difficult or almost impossible to automatically process the data package. For example, one package could contain a dimension called "payee" with field "name", while another would have a dimension "payment_target" with field "id", even though both would have the same meaning. The former OpenSpending Data Package specification clearly defined a set of mapping properties (payee, payor, date etc.) and their meanings. I think Fiscal Data Package should stick to that.

**Comment by stevage** [comment]
Agreed. The current spec says "We illustrate here some common dimensions.", which I'm hoping is shorthand for "We expect to define some standard dimensions and their semantics when we get a chance". My understanding was that the whole point of the "logical model" was to enable that kind of interoperability - otherwise you'd need a "super-logical model".

To move the discussion forward, let's suggest what those standard dimensions could be:

* `date`: when a transaction is dated (potentially with the need to distinguish between subtly different meanings like cash vs accrucal accounting etc)
* `classification`: functional classification of the spending/income, according to some referenced standard like COFOG, and possibly expressed as a multi-column hierarchy
* `organisation`: administrative unit doing the spending/receiving, possibly expressed as a multi-column hierarchy
* `payer`: *how does this relate to `organisation`?*
* `payee`: *this assumes the transaction is an outgoing one, does it need a more neutral name?*

**Comment by pwalsh** [comment]
Also partly related to https://github.com/openspending/fiscal-data-package/issues/44

**Comment by pwalsh** [comment]
@stevage just a few quick note on your explanation of the `classification` dimension. 

1. Classifications should not only be according to some referenced standard. Much (most...) data comes with some local (ad hoc, or otherwise) classification system, which can then be **mapped** to generic standards (and I think such mapping is not in the scope of the spec). One middle approach is to have a way to say "this is a functional classification scheme, and it **is** COFOG". An earlier version of this spec did this, [here](https://github.com/openspending/osep/pull/14/files#diff-33e55218209798854ac1233817c46e24R25) and [here](https://github.com/openspending/osep/blob/9006953cd164116a0e4b8eec1cd48006e8fb843e/osep-04.md#function)
2. It can be very useful to have explicit patterns for the various types of classification of spend data: notably functional and economic. I talked about that [a bit here](https://discuss.okfn.org/t/open-spending-data-structure-ideas-and-suggestions/300/15), and there was a [draft version of this in a previous version of this spec](https://github.com/pwalsh/osep/commit/05d21eac9160dea91672d1b88e1d99d9f1e4d29f#diff-86ed571c438ffbeae5f0f62e13d78e02R210)

**Comment by stevage** [comment]
That all sounds pretty good to me. So the three main hierarchy systems are functional, organisational, and economic - what's the last one about?

The only part I'd quibble with is putting `cofog` directly under the `functional`, maybe it would be cleaner to have:

```
functional: { 
  id: "blah", ...,
  codes: { cofog: "1234123", someothercode: "1324123" }
}
```

Anyway, obvious question: if this was proposed before, what happened to it?

**Comment by rgrp** [comment]
@marek-dudas a lot of work to provide recommendations / framework for the "content" has just gone in with https://github.com/openspending/fiscal-data-package/commit/1190f199504eaedd8cbed61fc3a7e88f93092c16 re #34. Do you want to take a look at v0.3.0-alpha4 and see if your concerns are addressed?

Ditto @stevage

**Comment by rgrp** [comment]
FIXED. Closing as believe fixed now with new setup and no comments from @marek-dudas or @stevage to contrary :-)
