### ISSUE TITLE
Is tooling proposed to author data package meta data?

### ISSUE THREAD

**Issue by timgdavies** [openspending/fiscal-data-package#72]
The current documentation is a relatively heavy read for anyone trying to work out exactly what they would have to do in order to publish their own data via FDP.

Are there any plans to either:

**(a) Provide more user-centred documentation?**

I suspect this would be very helpful to broaden engagement in the development process. 

**(b) Provide tooling for creating the FDP datapackage.json files?**

A tool to provide point-and-click mapping of tabular data would greatly hide the complexity of creating a datapackage.json file, and I suspect substantially increase the accessibility of the proposed model.

**Comment by pwalsh** [comment]
Hi @timgdavies 

**(a) User-centered documentation**

I agree this would be useful. I'd rather not have two types of documentation for a spec, so I think we need to iterate on the current spec so that it is more friendly.

Also note that we have many examples of data converted/packaged as Fiscal Data Package right here: 

https://github.com/os-data

Our work on the spec is **always** in reference to actual data, and that is essentially our testing ground right now.

**(b) tooling for creating FDP datapackage.json files**

We are actively working on a user interface to take CSV data, model it, and output a Fiscal Data Package descriptor. Please follow https://github.com/openspending/fiscal-data-packager to keep up with progress. 

Also note that Fiscal Data Package is at the core of the new OpenSpending platform we are working on, so expect a lot more tooling around the spec. For example, we are currently working on visualisation libs that can run directly off a Fiscal Data Package.

**Comment by rgrp** [comment]
@timgdavies does this answer your question for now? If so we'll close - otherwise please keep asking :-)

**Comment by timgdavies** [comment]
Thanks @pwalsh @rgrp 

Part (b) is definitely answered. Great to see this.

It might be useful to leave an issue open for (a) on documentation improvements to allow the average user to work out from the docs how to create a valid package.

It might also be useful to have an issue re: pointing to the sample data and tools from the docs - as again this would help people make decisions about piloting and adoption.

**Comment by akariv** [comment]
Can we close this, or is proper documentation still necessary?

**Comment by timgdavies** [comment]
If http://fiscal.dataprotocols.org/spec/ is the primary documentation then I would suggest there is definitely a need for some further iteration to make this accessible to adopters and users of the data. 

Earlier this year we added a 'getting started' section to OCDS docs, sitting parallel to the more technical reference on the standard, and this has proved pretty useful in helping adoption.

**Comment by pwalsh** [comment]
Moved to https://github.com/frictionlessdata/datapackage-fiscal/issues/4
