### ISSUE TITLE
Worked up example needed of transforming datasets with per-line "direction"

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#91]
A common pattern for budget data is to have the "direction" specified per-line.

| year | direction | amount |
|---|---|---|
| 2004 | expense | 1000 | 
| 2004 | revenue | 500 | 
| 2005 | expense | 300 |
| 2005 | revenue | 400 | 

Real example: http://opendata.paris.fr/explore/dataset/comptes-administratifs-principaux-ville-departement/?tab=table (column: *Sens (Dépense / Recette)*).

Given that we have [settled](https://github.com/openspending/fiscal-data-package/issues/37) on "direction" as a property of a measure, our model is incompatible with the file above.  Therefore, some guidance in the spec is necessary to demonstrate the best way to transform such datasets before loading into OpenSpending.

My sense is that the following straightforward transformation would be required for modeling the data:

| year | expense | revenue | 
|---|---|---|---|
| 2004 | 1000 | 0 | 
| 2004 | 0 | 500 | 
| 2005 | 300 | 0 |
| 2005 | 0 | 400 |

**Comment by pwalsh** [comment]
This is so common that I think it is a mistake to require transformation.

I wouldn't have thought that acknowledging direction as belonging to a measure means that it can't be declared on the budget line, as that is what mapping are intended for (physical to logical).

**Comment by pwalsh** [comment]
Hey @danfowler a bit more context for you here:


This very issue was raised here by me in September against the then current state of the spec:

https://github.com/openspending/fiscal-data-package/issues/37

Comments on the same problem by @pudo and myself from July (when `direction` was called `type`):

https://discuss.okfn.org/t/supporting-assets-and-liabilities-needed-for-openeconomy-org-au/452/3?u=pwalsh

And, an earlier issue raised by me on this tracker, in March, against the BDP spec: 

https://github.com/openspending/fiscal-data-package/issues/32

So, the two issues above from this issue tracker were actually marked as **resolved** with 0.3 of the FDP spec, yet this new issue you have opened indicates otherwise :).

**Comment by rgrp** [comment]
@pwalsh this issue is not #37 IMO as those relate to situation where the "direction" is a column e.g. you have a column for revenue and a column for expenditure. Not where you normalize this.

#32 is the issue as you describe. I closed that is INVALID possibly incorrectly now I re-read because i'd interpreted @trickvi comments as suggesting that we would always split out. I marked as INVALID because in v0.3 we no longer had the setup that @trickvi was referring to in terms of the required structure of the FDP. We could re-open #32 now i think.

**Comment by danfowler** [comment]
Thanks @pwalsh and @rgrp for the context.  I do think it is worth supporting this kind of dataset.

The idea behind this issue was to force some thinking about the implications of pushing direction to the measure without modification to how a measure is described.  It is probably too strong to say that making `direction` a property of measure makes this CSV structure incompatible, but in order to describe this data fully, we would need to change the way a measure is structured.  I have been doing some thinking about how I would possibly support this.  The keys "direction" and "phase" could be either strings as originally specified, or "source" objects (i.e. with "source" and "resource" keys) like "measure" itself, but with the addition of a optional `translation` array that maps properties in the source column to legit values in the spec (ordered like in the spec).  What do you think?

| year | Sens (Dépense / Recette) | amount |
|---|---|---|
| 2004 | Dépense | 1000 | 
| 2004 | Recette | 500 | 
| 2005 | Dépense | 300 |
| 2005 | Recette | 400 |  
```
{
  "name": "measure-name",
  "source": "amount",
  // "resource": "some-other-resource-if-applicable",
  "currency": "EUR",
  "direction": {
    "source": "Sens (Dépense / Recette)",
    // "resource": "some-other-resource-if-applicable",
    "translation": ["Dépense", "Recette"] // "MAY" property, order maps to order from spec: expenditure, revenue
  }
}

**Comment by rgrp** [comment]
I keep pushing for seeing the impact on code. Could we get a sense of what the implications would be for e.g. our aggregation code as we support this stuff. It certainly adds conceptual complexity but it may be worth it if we get to cover a significantly extended universe of source data.

**Comment by stevage** [comment]
Is there way of managing issues like this as a kind of "maybe in the future"?  That is, saying for now that our spec doesn't support it, and therefore transforms are needed, but leaving room in the spec to support it in the future? I think I agree with the need to keep the thing small and tight to allow for immediate implementation, but there should be room to grow.

That said, here's another way to handle this example:

```
{
  "name": "revenues",
  "source": "amount",
  "currency": "EUR",
  "direction": "revenue",
  "filter": {
    "source": "Sens (Dépense / Recette)",
    "value": "Recette"
  }
}
// repeat for expenditures
```

Lots of things become easy to handle if we allow expressions, filters or transformations to be directly expressed.

**Comment by danfowler** [comment]
@stevage Thanks for the "filter" example: I do like it :).  And thanks very much for the suggestion of "maybe in the future" issues as I've recently been thinking along similar lines. Perhaps we need a rough "roadmap" of sorts for the specification.

**Comment by pwalsh** [comment]
@danfowler @rgrp  would be good to address this in some way, as it is fairly common in published data.

**Comment by akariv** [comment]
We should probably move exactly in the opposite direction, as #141 suggests.

That is - the 'phase' and 'direction' attributes for measures should be used to populate their respective columns in the data while duplicating rows as necessary rather than the other way round.

**Comment by rgrp** [comment]
WONTFIX. We will not support interacting columns and having expense and revenue done via a column in the same data file. Users will have to normalize the data a bit in this case and split expense and revenue into separate files or change the signs of data (e.g. make revenue negative) themselves.
