### ISSUE TITLE
Representing Hierarchical Structure in Dimensions

### ISSUE THREAD

**Issue by danfowler** [openspending/fiscal-data-package#96]
Through discussion with @rgrp, we have come up with several different cases on the kinds of source data we should support and how we represent it in dimensions.

### Case 1 - Denormalized - No Unique ID for Classification

*Where there is no unique identifier for the classification (e.g. we do not have A.01 as an entry in a column).  This means in generating a normalized table structure you will need to generate identifiers and foreign key.*

| amount | level1 | level1_title | level2 | level2_title |
|---|---|---|---|---|
| 10 | A | Military | 01 | Planes |

### Case 2 - Denormalized, Unique ID for Classification

| amount | code | class_level1 | level1_title | level2 | level2_title |
|---|---|---|---|---|---|
| 10 | A.01 | A | Military | 01 | Planes |

### Case 3 - Normalized

| amount | class_code |
|---|---|
| 10 | A.01 |

| code | level1 | level1_title | level2 | level2_title |
|---|---|---|---|---|
| A.01 | A | Military | 01 | Planes |

## Logical Model 

All of the the above produce a logical model as follows:

**Fact Table**

| amount | class_code |
|---|---|
| 10 | A.01 |

class_code = code on classification table

**Classification Table**

| code | level1 | level1_title | level2 | level2_title |
|---|---|---|---|---|
| A.01 | A | Military | 01 | Planes |

**NOTE: we have denormalized the classification table a bit here -- see below for example of non-denormalized. Denormarlization is common because source data looks like this *and* it makes group by easier when we join ...**

## What do you need to be able to do / explain:

* How to generate normalization and foreign keys
  * Not actually clear atm
* Where to describe where fields in the logical model come from in physical model
  * ATM: we do this in standard way via `source`
  * Pretty easy except where no primary key (code) for classification 
* Hierarchical structure
  * At the moment in v0.3-alpha13 we do this via `level` keyword on the denormed levels 
  * Other options: use `parent` keyword to point to the parent field / attribute
  * Store parent information "in the data" - see below
* Label relationships e.g. level1_title labels level1
  * Why do we need to know this? When is it used? Is the client code using it able to be explicitly told where labels come from or should this be automated.
  * Is this a more generic requirement unrelated to classifications? (Probably)

**For the classification table: do we want to use a “parent” model or use some denormalization combined with simple “levels”?**

### Parent model:

| ID | Label | Parent | 
|---|---|---|---|
| 01.02 | XYZ | 01 |
| 01.02.03 | ABC | 01.02 |

### Partially denormed model:

| ID | level1 | level1_label | level2 | level2_label | level3 | level3_label |
|---|---|---|---|---|---|---|---|
| 01.02 |  01 | ... | 02 | .... | | |
| 01.02.03 |  01 | ... | 02 | ... | 03 | ...|

**Comment by pwalsh** [comment]
@danfowler can you show real world examples of each case above? Case 1 is the only one that looks like any data I've seen in an actual CSV file.

I'm going to give here two real world examples and show how they would be represented in the spec as I see it. 

I'm not inventing here anything that has not [been](https://discuss.okfn.org/t/open-spending-data-structure-ideas-and-suggestions/300/19) [discussed](https://github.com/openspending/fiscal-data-package/issues/49) [before](https://github.com/openspending/fiscal-data-package/issues/48), and in fact some of this is reflected in [earlier versions of the spec](https://github.com/openspending/osep/blob/e782aa56c7ae494fbb720a175fba9941208ea0b2/_includes/with-classification/datapackage.json#L1).

## 0. Basic example, no hierarchy, single field for dimension

```
# data.csv
year,category,amount
2006,0100,600
2006,0200,500
```

```
{
  "resources": [ { "path": "data.csv", "name": "data" } ],
  "model": {
    "measures": {
      "amount": { "source": "amount" }
    },
    "dimensions": {
      "economic": {
        "dimensionType": "classification",
        "classificationType": "economic",
        "attributes": { "id": "category" }    
      }
    }
  }
}
```

* **note**: When a dimension has a single attribute, this attribute is its unique identifier, and by definition the primary key of the dimension. We codify this with `attribute.id` (was part of OpenSpending Data Package where `id` and `title` attributes has *meaning*)

## 1. Basic example, no hierarchy, multiple fields for dimension

```
# data.csv
year,category_code,category_name,category_description,amount
2006,0100,Education,Funds for preschools,600
2006,0200,Defense,Funds for tanks,500
```

```
{
  "resources": [ { "path": "data.csv", "name": "data" } ],
  "model": {
    "measures": {
      "amount": { "source": "amount" }
    },
    "dimensions": {
      "economic": {
        "dimensionType": "classification",
        "classificationType": "economic",
        "attributes": { "id": "category_code", "title": "category_name", "description": "category_description" }    
      }
    }
  }
}
```

* **note**: When a dimension has a multiple attributes, *one* of them is the unique identifier, and by definition the primary key of the dimension. We codify this with `attribute.id` (was part of OpenSpending Data Package where `id` and `title` attributes has *meaning*), and we choose another as `attribute.title`. There are no further restrictions: `attribute.description` may be useful but there is no need to codify it in the spec: this example can work without it.

## 2. A denormalised resource, multiple levels, one field per dimension level

Taken from [BOOST Paraguay](https://github.com/os-data/boost-paraguay), reduced to minimum to demonstrate example:

```
# data.csv
YEAR,ECON4,ECON5,PAID
2006,100 - PERSONAL SERVICES,110 - BASIC COMPENSTION,67532
2006,100 - PERSONAL SERVICES,120 - TEMPORARY COMPENSATION,309
```

```
{
  "resources": [ { "path": "data.csv", "name": "data" } ],
  "model": {
    "measures": {
      "amount": { "source": "PAID" }
    },
    "dimensions": {
      "economic": {
        "dimensionType": "classification",
        "classificationType": "economic",
        "attributes": [ { "id": "ECON4" }, { "id": "ECON5" } ]    
      }
    }
  }
}
```

## 3. A denormalised resource, multiple levels, multiple fields per dimension level

Because we are familiar with the BOOST Paraguay data, we see that in an ideal world, the source data would look like this (and if you look at the https://github.com/os-data registry, you'll see many examples of this pattern):

```
# data.csv
YEAR,ECON4,ECON4_NAME,ECON5,ECON5_NAME,PAID
2006,100,PERSONAL SERVICES,110,BASIC COMPENSTION,67532
2006,100,PERSONAL SERVICES,120,TEMPORARY COMPENSATION,309
```

```
{
  "resources": [ { "path": "data.csv", "name": "data" } ],
  "model": {
    "measures": {
      "amount": { "source": "PAID" }
    },
    "dimensions": {
      "economic": {
        "dimensionType": "classification",
        "classificationType": "economic",
        "attributes": [ { "id": "ECON4", "title": "ECON4_NAME" }, { "id": "ECON5" , "title": "ECON5_NAME" } ]    
      }
    }
  }
}
```

* **note**: This is all the information needed to build a self-referencing (parent-child) economic dimension - be it a database table or some other data structure


## 4. A normalised set of resources

Again, I'll use the same BOOST data as example here for consistency, but there are other examples in `os-data`, in the original issue I opened for this ( #49 ), and in earlier versions of the spec when it was OSDP.

```
# data.csv
YEAR,ECON,PAID
2006,110,67532
2006,120,309

# econ.csv
CODE,PARENT,NAME
100,,PERSONAL SERVICES
110,100,BASIC COMPENSATION
120,100,TEMPORARY COMPENSATION
```

```
{
  "resources": [ 
    { "path": "data.csv", "name": "data", "schema": ... ECON column is FK to econ resource... },
    { "path": "econ.csv", "name": "econ",  }
  ],
  "model": {
    "measures": {
      "amount": { "source": "PAID" }
    },
    "dimensions": {
      "economic": {
        "dimensionType": "classification",
        "classificationType": "economic",
        "attributes": { "id": "ECON/CODE", "title": "ECON/NAME" }  
      }
    }
  }
}
```

* **note**: I've used an older-style shorthand in `attributes`, special-casing `/` as the accessor symbol on the foreign key (`ECON/{FIELD_ON_REFERENCED_TABLE}`). Not sure in the current spec how you would write this accessor via a FK. 
* **note**: Like in the denormalised version in example 3 above, this is all the information needed to build a self-referencing (parent-child) economic dimension - be it a database table or some other data structure.

**Comment by pudo** [comment]
As @jazzido points out, it's really useful to check the [Mondrian](http://mondrian.pentaho.com/documentation/schema.php#Multiple_hierarchies) documentation on this. Based on this, here's a few notes:

* We need to be clear about whether the question of how resources are joined is in a direct way related to dimensional modelling. This is true in Mondrian (where you can specify a table name and a foreign key on the fact table for each dimension), but it [does not seem to be a hard constraint in DSPL](https://developers.google.com/public-data/docs/developer_guide#tables).
  * My approach in SpenDB has been to get a "dimensions on fact table" approach going and worry about internal normalisation later, and I wonder if the FDP spec wouldn't benefit from similar simplification. Multiple resources are cool, but they just make all of the UX and data management an order of magnitude more complex.

* It's not clear to me whether we have decided the levels of granularity here. Most OLAP systems seem to have three model components: Dimensions (ie. topical groupings), Hierarchies (ways to break them down), and Levels (the units of a hierarchy).
  * In this discussion, there sometimes seems to be an implicit assumption that we'll only have a single hierarchy per dimension. If so, this should be spelled out.
  * We should also be clear as to whether a level is only composed of a single attribute or can contain multiple attributes. The examples indicate the latter.
  * I can't see the need for a parent to be specified explicitly in the data, this should be possible to infer easily through the existing data.

To give a concrete proposal, I'd pitch this - which is based on the assumption of a single hierarchy with multi-attribute levels:

```json
"model": {
    "measures": {
      "amount": { "source": "PAID" }
    },
    "dimensions": {
      "economic": {
        "dimensionType": "classification",
        "classificationType": "economic",
        "levels": [
          {"attributes": {"econ1_id": {"field": "ECON1/CODE"}, "econ1_title": {"field": "ECON1/NAME"}}},
          {"attributes": {"econ2_id": {"field": "ECON2/CODE"}, "econ2_title": {"field": "ECON2/NAME"}}},
          {"attributes": {"econ3_id": {"field": "ECON3/CODE"}, "econ3_title": {"field": "ECON3/NAME"}}},
        ]
      }
    }
  }
```

---

More generally, I'm getting the sense that this discussion is a bit torn up by the two overlapping use cases of the FDP: serving as a public/general data exchange and annotation format, and serving as the internal data model for OpenSpending Next.

Defining hierarchies in either case has slightly different semantics - in one case, you're merely trying to describe the semantics of the data, while in the other, you're trying to lay out query sets that are going to be useful (but not necessarily "inherent" in the data).

**Comment by danfowler** [comment]
@pudo When I look at your example, I see a transformation of Paul's suggestion of nested objects in an array with the following changes:

- s/source/field/ (ref https://github.com/openspending/fiscal-data-package/issues/93)
- s/attributes/levels/ (ref Mondrian https://github.com/openspending/fiscal-data-package/issues/48#issuecomment-155032825)
- You group and give a name to the elements of a given position in the hierarchy (your `attributes`), which looks nicer and is more explicit, but is perhaps not strictly necessary?  Is there any other information that should be shared between columns at a given level of a hierarchy?

**Comment by rgrp** [comment]
My comments:

A.  think we want to split out the "label" question to a separate issue and not get confused on this. I note that Paul's Example 1 already starts to muddy the water further here ;-). Thus, for the purpose of indicating hierarchical structure in our logical model we only have a level made up of one attribute 

B. Having re-read this i think we want to replace `level` with parent which is the name of another attribute / field in the dimension. This means we can:

* Support multiple hierarchies in a single dimension
* Support multiple children

```
# data.csv
YEAR,ECON4,ECON4-TITLE,ECON5, ECON5-TITLE,PAID
2006,100, PERSONAL SERVICES,110, BASIC COMPENSATION,67532

{
  "resources": [ { "path": "data.csv", "name": "data" } ],
  "model": {
    "measures": {
      "amount": { "source": "PAID" }
    },
    "dimensions": {
      "economic": {
        "dimensionType": "classification",
        "classificationType": "economic",
        "attributes": { 
           "id": .... # see comment below about identifiers
           "econ4": {
              "source": "ECON4"
           },
           "econ4_title": {
             "source": "ECON4-TITLE"
           },
           "econ5": {
              "source": "ECON5",
              "parent": "econ4"
           },
           "econ5-title": ...
         ]    
      }
    }
  }
}
```

What is still unresolved is how you deal with generating unique identifiers. Perhaps we can abuse the `constant` keyword and have autoincrement - this *should* definitely be a separate issue if we propose it.

**Comment by pwalsh** [comment]
@rgrp putting aside all else, I'm interested in your use of `parent`, the search for an `id` that is not in the data itself, and lastly, I want to make some notes about standardisation across data packages.

### parent

By not relying on array order I suppose you can build more complex hierarchies. Fair enough. but why not this:

```
"attributes": [
  { "econ4": { "source": "ECON4" }, "econ4_title": { "source": "ECON4-TITLE" }, "parent": null }
  { "econ5": { "source": "ECON5" }, "econ5_title": { "source": "ECON5-TITLE" }, "parent": 100 }
]
```

instead of this:

```
"attributes": { 
  "econ4": { "source": "ECON4" },
  "econ4_title": { "source": "ECON4-TITLE" },
  "econ5": { "source": "ECON5", "parent": "econ4" },
  "econ5-title": { ... }
}
```

I guess I don't understand why you don't want to represent the "code" and the "title" fields together, and treat them as the attribute group that they are :).

### id

Our data likely has a primary key: the code of the dimension. If we can't trust uniqueness of the "code" itself (we *can't* in a hierarchy, we *can* in a flat dimension), then we have other options:

* a composite key of all values in the attribute group
* hash the values of the attribute group (like above, but represented as a single property)
* use the path to the code in the tree (from top of tree to code)

Any of these is preferable to an auto-incrementing solution IMHO. **All** of these would guarantee a primary key that is consistent for the object, no matter what backend, nor when it is written to such a backend. This is super useful for a distributed system like OpenSpending Next, but I'll leave it to you and @danfowler to work out what is best for the spec :). 

### standardisation

In the spec, we don't care what fields are called in the user-supplied resource. That is great! However, why treat the mapping the same? Would we not want *consumers* of the spec to expect certain patterns?

Example:

Why:

```
"attributes": { 
  "econ4": { "source": "ECON4" },
  "econ4_title": { "source": "ECON4-TITLE" },
  "econ5": { "source": "ECON5" },
  "econ5-title": { "source": "ECON5-TITLE" }
}
```

and not:

```
"attributes": [
  { "code": { "source": "ECON4" }, "title": { "source": "ECON4-TITLE" }, "parent": null }
  { "code": { "source": "ECON5" }, "title": { "source": "ECON5-TITLE" }, "parent": 100 }
]
```

?

**Comment by rgrp** [comment]
@pwalsh i just don't want compound attributes around - how does this get mapped into a backend data model etc. Why not just keep it flat. I think binding together the question of hierarchy and the question of how to tie together different bundles of attributes is a mistake and will confuse matters here ;-)

Re `id`: let's split that out. It really does not matter right now *too much* afaict.

Re standardization on naming: I'm totally happy on that but think it is more of a pattern / SHOULD type of thing than a MUST but i'm easy either way.

**Comment by pwalsh** [comment]
@rgrp so should we again break this issue out into distinct sub issues?

I'm really confused by the idea of not wanting compound attributes. It makes our package more "lossy" than it needs to be. 

In the example data below, not having compound attributes means that the `*_NAME` fields are essentially useless, when in fact they provide very useful information on the classification of a budget line. 

In the best case, in order to get those `*_NAME` fields into some system that works with FDP, we'd be encouraging, nay requiring, publishers and consumers of FDP to treat, for example, `ECON4 ` and `ECON4_NAME` as distinct dimensions, and in the worst case, to simply ignore those descriptive fields and only model the codes themselves. 

This would mean, in my opinion, that our model doesn't reflect the facts that it models very accurately: clearly, when a human reads this sample, `ECON4_NAME` is a description field for `ECON4`, not a distinct dimension.

```
# data.csv
YEAR,ECON4,ECON4_NAME,ECON5,ECON5_NAME,PAID
2006,100,PERSONAL SERVICES,110,BASIC COMPENSTION,67532
2006,100,PERSONAL SERVICES,120,TEMPORARY COMPENSATION,309
```
